DROP TABLE LOS_BORBOTONES.Rol
DROP TABLE LOS_BORBOTONES.Funcionalidad
DROP TABLE LOS_BORBOTONES.Funcionalidad_X_Rol
DROP SCHEMA LOS_BORBOTONES

CREATE SCHEMA [LOS_BORBOTONES] AUTHORIZATION [dbo]

CREATE TABLE LOS_BORBOTONES.Rol (

	idRol	INT			NOT NULL,
	Nombre	VARCHAR(45) NOT NULL,
	Estado	VARCHAR(45)	NOT NULL,
	PRIMARY KEY(idRol)

)

CREATE TABLE LOS_BORBOTONES.Funcionalidad (

	idFuncionalidad	INT			NOT NULL,
	Descripcion 	VARCHAR(45)	NOT NULL,
	PRIMARY KEY (idFuncionalidad)

)

CREATE TABLE LOS_BORBOTONES.Funcionalidad_X_Rol (

	idFuncionalidad	INT			NOT NULL,
	idRol			INT			NOT NULL,
	PRIMARY KEY (idFuncionalidad, idRol)

)